<?php

namespace DeepSeek\Traits\Client;

use DeepSeek\Enums\Queries\QueryRoles;

trait HasToolsFunctionCalling
{
    /**
     * @param  array  $tools  A list of tools the model may call.
     * @return self The current instance for method chaining.
     */
    public function setTools(array $tools): self
    {
        $this->tools = $tools;

        return $this;
    }

    /**
     * Append a single function tool with structured-output strict mode enabled.
     *
     * Strict mode is a DeepSeek Beta feature: when enabled the model is
     * guaranteed to produce tool-call arguments that conform exactly to the
     * provided JSON schema. See the DeepSeek API reference for caveats.
     *
     * This helper is purely additive — it appends to whatever the existing
     * setTools() / prior setStrictTool() calls have already stored, so it
     * never silently replaces an existing tool list.
     *
     * @param  string  $name  Function name.
     * @param  array  $parameters  JSON-schema object describing the function arguments.
     * @param  string|null  $description  Optional human-readable description.
     * @return self The current instance for method chaining.
     */
    public function setStrictTool(string $name, array $parameters, ?string $description = null): self
    {
        $this->tools = $this->tools ?? [];

        $function = ['name' => $name];

        if ($description !== null) {
            $function['description'] = $description;
        }

        $function['parameters'] = $parameters;
        $function['strict'] = true;

        $this->tools[] = [
            'type' => 'function',
            'function' => $function,
        ];

        return $this;
    }

    /**
     * Add a query tool calls to the accumulated queries list.
     *
     * @param  array  $toolCalls  The tool calls generated by the model, such as function calls.
     * @return self The current instance for method chaining.
     */
    public function queryToolCall(array $toolCalls, string $content, ?string $role = null): self
    {
        $this->queries[] = $this->buildToolCallQuery($toolCalls, $content, $role);

        return $this;
    }

    public function buildToolCallQuery(array $toolCalls, string $content, ?string $role = null): array
    {
        $query = [
            'role' => $role ?: QueryRoles::ASSISTANT->value,
            'tool_calls' => $toolCalls,
            'content' => $content,
        ];

        return $query;
    }

    /**
     * Add a query tool to the accumulated queries list.
     *
     * @return self The current instance for method chaining.
     */
    public function queryTool(string $toolCallId, string $content, ?string $role = null): self
    {
        $this->queries[] = $this->buildToolQuery($toolCallId, $content, $role);

        return $this;
    }

    public function buildToolQuery(string $toolCallId, string $content, ?string $role): array
    {
        $query = [
            'role' => $role ?: QueryRoles::TOOL->value,
            'tool_call_id' => $toolCallId,
            'content' => $content,
        ];

        return $query;
    }
}
